version: '3'

services:
  db-dev:
    image: mysql:8.0
    container_name: toeic-db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '$DB_PORT:3306'
    volumes:
      - toeic-dbdata-dev:/var/lib/mysql/
    networks:
      - toeic-dev-network

  # backend-dev:
  #   container_name: blog-backend-dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   env_file:
  #     - .env
  #   ports:
  #     - '$PORT:$PORT'
  #   depends_on:
  #     - db-dev
  #   command: 'npm run migration:run && npm start:dev'
  #   volumes:
  #     - ./src:/home/node/app/src
  #   networks:
  #     - toeic-dev-network

networks:
  toeic-dev-network:
    driver: bridge
volumes:
  toeic-dbdata-dev:
    driver: local
